# Generated by scripts/gen_ignore_cases.exs. DO NOT EDIT BY HAND.
#
# Every expectation was produced by `git check-ignore` (git version 2.48.1)
# running against the scenario's materialized file layout. `expected` is
# the exit status of check-ignore -q; `rule` is the matched pattern from
# check-ignore -v (present even for negated matches, as in git).
#
# Regenerate: mix run scripts/gen_ignore_cases.exs and review the diff.
[
  %{
    name: "basic negation: \"other.beam\" (file)",
    casefold: false,
    files: %{".gitignore" => "*.beam\n!important.beam\n"},
    path: "other.beam",
    type: :file,
    expected: true,
    rule: %{line: 1, pattern: "*.beam", source: ".gitignore"}
  },
  %{
    name: "basic negation: \"important.beam\" (file)",
    casefold: false,
    files: %{".gitignore" => "*.beam\n!important.beam\n"},
    path: "important.beam",
    type: :file,
    expected: false,
    rule: %{line: 2, pattern: "!important.beam", source: ".gitignore"}
  },
  %{
    name: "basic negation: \"lib/foo.beam\" (file)",
    casefold: false,
    files: %{".gitignore" => "*.beam\n!important.beam\n"},
    path: "lib/foo.beam",
    type: :file,
    expected: true,
    rule: %{line: 1, pattern: "*.beam", source: ".gitignore"}
  },
  %{
    name: "basic negation: \"lib/important.beam\" (file)",
    casefold: false,
    files: %{".gitignore" => "*.beam\n!important.beam\n"},
    path: "lib/important.beam",
    type: :file,
    expected: false,
    rule: %{line: 2, pattern: "!important.beam", source: ".gitignore"}
  },
  %{
    name: "dir-only parent exclusion blocks re-include: \"build\" (directory)",
    casefold: false,
    files: %{".gitignore" => "build/\n!build/keep.txt\n"},
    path: "build",
    type: :directory,
    expected: true,
    rule: %{line: 1, pattern: "build/", source: ".gitignore"}
  },
  %{
    name: "dir-only parent exclusion blocks re-include: \"build/keep.txt\" (file)",
    casefold: false,
    files: %{".gitignore" => "build/\n!build/keep.txt\n"},
    path: "build/keep.txt",
    type: :file,
    expected: true,
    rule: %{line: 1, pattern: "build/", source: ".gitignore"}
  },
  %{
    name: "dir-only parent exclusion blocks re-include: \"build/other.txt\" (file)",
    casefold: false,
    files: %{".gitignore" => "build/\n!build/keep.txt\n"},
    path: "build/other.txt",
    type: :file,
    expected: true,
    rule: %{line: 1, pattern: "build/", source: ".gitignore"}
  },
  %{
    name: "dir-only parent exclusion blocks re-include: \"build/sub/deep.txt\" (file)",
    casefold: false,
    files: %{".gitignore" => "build/\n!build/keep.txt\n"},
    path: "build/sub/deep.txt",
    type: :file,
    expected: true,
    rule: %{line: 1, pattern: "build/", source: ".gitignore"}
  },
  %{
    name: "contents-only exclusion allows re-include: \"build\" (directory)",
    casefold: false,
    files: %{".gitignore" => "build/*\n!build/keep.txt\n"},
    path: "build",
    type: :directory,
    expected: false,
    rule: nil
  },
  %{
    name: "contents-only exclusion allows re-include: \"build/keep.txt\" (file)",
    casefold: false,
    files: %{".gitignore" => "build/*\n!build/keep.txt\n"},
    path: "build/keep.txt",
    type: :file,
    expected: false,
    rule: %{line: 2, pattern: "!build/keep.txt", source: ".gitignore"}
  },
  %{
    name: "contents-only exclusion allows re-include: \"build/other.txt\" (file)",
    casefold: false,
    files: %{".gitignore" => "build/*\n!build/keep.txt\n"},
    path: "build/other.txt",
    type: :file,
    expected: true,
    rule: %{line: 1, pattern: "build/*", source: ".gitignore"}
  },
  %{
    name: "plain anchored rule excludes directory contents: \"foo\" (directory)",
    casefold: false,
    files: %{".gitignore" => "/foo\n"},
    path: "foo",
    type: :directory,
    expected: true,
    rule: %{line: 1, pattern: "/foo", source: ".gitignore"}
  },
  %{
    name: "plain anchored rule excludes directory contents: \"foo/bar\" (file)",
    casefold: false,
    files: %{".gitignore" => "/foo\n"},
    path: "foo/bar",
    type: :file,
    expected: true,
    rule: %{line: 1, pattern: "/foo", source: ".gitignore"}
  },
  %{
    name: "plain anchored rule excludes directory contents: \"foo/sub/deep.txt\" (file)",
    casefold: false,
    files: %{".gitignore" => "/foo\n"},
    path: "foo/sub/deep.txt",
    type: :file,
    expected: true,
    rule: %{line: 1, pattern: "/foo", source: ".gitignore"}
  },
  %{
    name: "plain anchored rule excludes directory contents: \"other/foo/bar\" (file)",
    casefold: false,
    files: %{".gitignore" => "/foo\n"},
    path: "other/foo/bar",
    type: :file,
    expected: false,
    rule: nil
  },
  %{
    name: "basename rule matches directories at any depth: \"node_modules\" (directory)",
    casefold: false,
    files: %{".gitignore" => "node_modules\n"},
    path: "node_modules",
    type: :directory,
    expected: true,
    rule: %{line: 1, pattern: "node_modules", source: ".gitignore"}
  },
  %{
    name: "basename rule matches directories at any depth: \"apps/node_modules\" (directory)",
    casefold: false,
    files: %{".gitignore" => "node_modules\n"},
    path: "apps/node_modules",
    type: :directory,
    expected: true,
    rule: %{line: 1, pattern: "node_modules", source: ".gitignore"}
  },
  %{
    name: "basename rule matches directories at any depth: \"apps/node_modules/foo.js\" (file)",
    casefold: false,
    files: %{".gitignore" => "node_modules\n"},
    path: "apps/node_modules/foo.js",
    type: :file,
    expected: true,
    rule: %{line: 1, pattern: "node_modules", source: ".gitignore"}
  },
  %{
    name:
      "basename rule matches directories at any depth: \"apps/web/node_modules/pkg/index.js\" (file)",
    casefold: false,
    files: %{".gitignore" => "node_modules\n"},
    path: "apps/web/node_modules/pkg/index.js",
    type: :file,
    expected: true,
    rule: %{line: 1, pattern: "node_modules", source: ".gitignore"}
  },
  %{
    name:
      "re-include inside basename-excluded directory is blocked: \"node_modules/keep.js\" (file)",
    casefold: false,
    files: %{".gitignore" => "node_modules\n!node_modules/keep.js\n"},
    path: "node_modules/keep.js",
    type: :file,
    expected: true,
    rule: %{line: 1, pattern: "node_modules", source: ".gitignore"}
  },
  %{
    name:
      "re-include inside basename-excluded directory is blocked: \"apps/node_modules/keep.js\" (file)",
    casefold: false,
    files: %{".gitignore" => "node_modules\n!node_modules/keep.js\n"},
    path: "apps/node_modules/keep.js",
    type: :file,
    expected: true,
    rule: %{line: 1, pattern: "node_modules", source: ".gitignore"}
  },
  %{
    name: "dir-only rule ignores a directory: \"cache\" (directory)",
    casefold: false,
    files: %{".gitignore" => "cache/\n"},
    path: "cache",
    type: :directory,
    expected: true,
    rule: %{line: 1, pattern: "cache/", source: ".gitignore"}
  },
  %{
    name: "dir-only rule ignores a directory: \"cache/entry\" (file)",
    casefold: false,
    files: %{".gitignore" => "cache/\n"},
    path: "cache/entry",
    type: :file,
    expected: true,
    rule: %{line: 1, pattern: "cache/", source: ".gitignore"}
  },
  %{
    name: "dir-only rule ignores a directory: \"deep/cache\" (directory)",
    casefold: false,
    files: %{".gitignore" => "cache/\n"},
    path: "deep/cache",
    type: :directory,
    expected: true,
    rule: %{line: 1, pattern: "cache/", source: ".gitignore"}
  },
  %{
    name: "dir-only rule ignores a directory: \"deep/cache/entry\" (file)",
    casefold: false,
    files: %{".gitignore" => "cache/\n"},
    path: "deep/cache/entry",
    type: :file,
    expected: true,
    rule: %{line: 1, pattern: "cache/", source: ".gitignore"}
  },
  %{
    name: "dir-only rule does not match a file: \"cache\" (file)",
    casefold: false,
    files: %{".gitignore" => "cache/\n"},
    path: "cache",
    type: :file,
    expected: false,
    rule: nil
  },
  %{
    name: "anchoring: \"tmp\" (directory)",
    casefold: false,
    files: %{".gitignore" => "/tmp\ndoc/frotz\nsrc/*.beam\n"},
    path: "tmp",
    type: :directory,
    expected: true,
    rule: %{line: 1, pattern: "/tmp", source: ".gitignore"}
  },
  %{
    name: "anchoring: \"nested/tmp\" (directory)",
    casefold: false,
    files: %{".gitignore" => "/tmp\ndoc/frotz\nsrc/*.beam\n"},
    path: "nested/tmp",
    type: :directory,
    expected: false,
    rule: nil
  },
  %{
    name: "anchoring: \"doc/frotz\" (directory)",
    casefold: false,
    files: %{".gitignore" => "/tmp\ndoc/frotz\nsrc/*.beam\n"},
    path: "doc/frotz",
    type: :directory,
    expected: true,
    rule: %{line: 2, pattern: "doc/frotz", source: ".gitignore"}
  },
  %{
    name: "anchoring: \"a/doc/frotz\" (directory)",
    casefold: false,
    files: %{".gitignore" => "/tmp\ndoc/frotz\nsrc/*.beam\n"},
    path: "a/doc/frotz",
    type: :directory,
    expected: false,
    rule: nil
  },
  %{
    name: "anchoring: \"src/foo.beam\" (file)",
    casefold: false,
    files: %{".gitignore" => "/tmp\ndoc/frotz\nsrc/*.beam\n"},
    path: "src/foo.beam",
    type: :file,
    expected: true,
    rule: %{line: 3, pattern: "src/*.beam", source: ".gitignore"}
  },
  %{
    name: "anchoring: \"apps/src/foo.beam\" (file)",
    casefold: false,
    files: %{".gitignore" => "/tmp\ndoc/frotz\nsrc/*.beam\n"},
    path: "apps/src/foo.beam",
    type: :file,
    expected: false,
    rule: nil
  },
  %{
    name: "trailing spaces: \"artifact\" (file)",
    casefold: false,
    files: %{".gitignore" => "artifact   \nkeep\\ \n"},
    path: "artifact",
    type: :file,
    expected: true,
    rule: %{line: 1, pattern: "artifact", source: ".gitignore"}
  },
  %{
    name: "trailing spaces: \"keep \" (file)",
    casefold: false,
    files: %{".gitignore" => "artifact   \nkeep\\ \n"},
    path: "keep ",
    type: :file,
    expected: true,
    rule: %{line: 2, pattern: "keep\\ ", source: ".gitignore"}
  },
  %{
    name: "trailing spaces: \"keep\" (file)",
    casefold: false,
    files: %{".gitignore" => "artifact   \nkeep\\ \n"},
    path: "keep",
    type: :file,
    expected: false,
    rule: nil
  },
  %{
    name: "escaped leading hash and bang: \"#secret\" (file)",
    casefold: false,
    files: %{".gitignore" => "\\#secret\n\\!secret\n"},
    path: "#secret",
    type: :file,
    expected: true,
    rule: %{line: 1, pattern: "\\#secret", source: ".gitignore"}
  },
  %{
    name: "escaped leading hash and bang: \"!secret\" (file)",
    casefold: false,
    files: %{".gitignore" => "\\#secret\n\\!secret\n"},
    path: "!secret",
    type: :file,
    expected: true,
    rule: %{line: 2, pattern: "\\!secret", source: ".gitignore"}
  },
  %{
    name: "globstar rules: \"logs\" (directory)",
    casefold: false,
    files: %{".gitignore" => "**/logs\nbuild/**\na/**/b\n"},
    path: "logs",
    type: :directory,
    expected: true,
    rule: %{line: 1, pattern: "**/logs", source: ".gitignore"}
  },
  %{
    name: "globstar rules: \"x/y/logs\" (directory)",
    casefold: false,
    files: %{".gitignore" => "**/logs\nbuild/**\na/**/b\n"},
    path: "x/y/logs",
    type: :directory,
    expected: true,
    rule: %{line: 1, pattern: "**/logs", source: ".gitignore"}
  },
  %{
    name: "globstar rules: \"build\" (directory)",
    casefold: false,
    files: %{".gitignore" => "**/logs\nbuild/**\na/**/b\n"},
    path: "build",
    type: :directory,
    expected: false,
    rule: nil
  },
  %{
    name: "globstar rules: \"build/out.o\" (file)",
    casefold: false,
    files: %{".gitignore" => "**/logs\nbuild/**\na/**/b\n"},
    path: "build/out.o",
    type: :file,
    expected: true,
    rule: %{line: 2, pattern: "build/**", source: ".gitignore"}
  },
  %{
    name: "globstar rules: \"build/sub/out.o\" (file)",
    casefold: false,
    files: %{".gitignore" => "**/logs\nbuild/**\na/**/b\n"},
    path: "build/sub/out.o",
    type: :file,
    expected: true,
    rule: %{line: 2, pattern: "build/**", source: ".gitignore"}
  },
  %{
    name: "globstar rules: \"a/b\" (directory)",
    casefold: false,
    files: %{".gitignore" => "**/logs\nbuild/**\na/**/b\n"},
    path: "a/b",
    type: :directory,
    expected: true,
    rule: %{line: 3, pattern: "a/**/b", source: ".gitignore"}
  },
  %{
    name: "globstar rules: \"a/x/b\" (directory)",
    casefold: false,
    files: %{".gitignore" => "**/logs\nbuild/**\na/**/b\n"},
    path: "a/x/b",
    type: :directory,
    expected: true,
    rule: %{line: 3, pattern: "a/**/b", source: ".gitignore"}
  },
  %{
    name: "globstar rules: \"a/x/y/b\" (directory)",
    casefold: false,
    files: %{".gitignore" => "**/logs\nbuild/**\na/**/b\n"},
    path: "a/x/y/b",
    type: :directory,
    expected: true,
    rule: %{line: 3, pattern: "a/**/b", source: ".gitignore"}
  },
  %{
    name: "globstar rules: \"z/a/b\" (directory)",
    casefold: false,
    files: %{".gitignore" => "**/logs\nbuild/**\na/**/b\n"},
    path: "z/a/b",
    type: :directory,
    expected: false,
    rule: nil
  },
  %{
    name: "leading globstar dir-only: \"temp\" (directory)",
    casefold: false,
    files: %{".gitignore" => "**/temp/\n"},
    path: "temp",
    type: :directory,
    expected: true,
    rule: %{line: 1, pattern: "**/temp/", source: ".gitignore"}
  },
  %{
    name: "leading globstar dir-only: \"x/temp\" (directory)",
    casefold: false,
    files: %{".gitignore" => "**/temp/\n"},
    path: "x/temp",
    type: :directory,
    expected: true,
    rule: %{line: 1, pattern: "**/temp/", source: ".gitignore"}
  },
  %{
    name: "leading globstar dir-only: \"x/temp/f.txt\" (file)",
    casefold: false,
    files: %{".gitignore" => "**/temp/\n"},
    path: "x/temp/f.txt",
    type: :file,
    expected: true,
    rule: %{line: 1, pattern: "**/temp/", source: ".gitignore"}
  },
  %{
    name: "wildcards and classes: \"filea.txt\" (file)",
    casefold: false,
    files: %{".gitignore" => "file?.txt\n[a-c].txt\n*.sw[po]\n"},
    path: "filea.txt",
    type: :file,
    expected: true,
    rule: %{line: 1, pattern: "file?.txt", source: ".gitignore"}
  },
  %{
    name: "wildcards and classes: \"file.txt\" (file)",
    casefold: false,
    files: %{".gitignore" => "file?.txt\n[a-c].txt\n*.sw[po]\n"},
    path: "file.txt",
    type: :file,
    expected: false,
    rule: nil
  },
  %{
    name: "wildcards and classes: \"b.txt\" (file)",
    casefold: false,
    files: %{".gitignore" => "file?.txt\n[a-c].txt\n*.sw[po]\n"},
    path: "b.txt",
    type: :file,
    expected: true,
    rule: %{line: 2, pattern: "[a-c].txt", source: ".gitignore"}
  },
  %{
    name: "wildcards and classes: \"d.txt\" (file)",
    casefold: false,
    files: %{".gitignore" => "file?.txt\n[a-c].txt\n*.sw[po]\n"},
    path: "d.txt",
    type: :file,
    expected: false,
    rule: nil
  },
  %{
    name: "wildcards and classes: \"x.swp\" (file)",
    casefold: false,
    files: %{".gitignore" => "file?.txt\n[a-c].txt\n*.sw[po]\n"},
    path: "x.swp",
    type: :file,
    expected: true,
    rule: %{line: 3, pattern: "*.sw[po]", source: ".gitignore"}
  },
  %{
    name: "wildcards and classes: \"x.swq\" (file)",
    casefold: false,
    files: %{".gitignore" => "file?.txt\n[a-c].txt\n*.sw[po]\n"},
    path: "x.swq",
    type: :file,
    expected: false,
    rule: nil
  },
  %{
    name: "comments blank lines and crlf: \"foo\" (file)",
    casefold: false,
    files: %{".gitignore" => "# comment\n\nfoo\r\nbar\n"},
    path: "foo",
    type: :file,
    expected: true,
    rule: %{line: 3, pattern: "foo", source: ".gitignore"}
  },
  %{
    name: "comments blank lines and crlf: \"bar\" (file)",
    casefold: false,
    files: %{".gitignore" => "# comment\n\nfoo\r\nbar\n"},
    path: "bar",
    type: :file,
    expected: true,
    rule: %{line: 4, pattern: "bar", source: ".gitignore"}
  },
  %{
    name: "comments blank lines and crlf: \"# comment\" (file)",
    casefold: false,
    files: %{".gitignore" => "# comment\n\nfoo\r\nbar\n"},
    path: "# comment",
    type: :file,
    expected: false,
    rule: nil
  },
  %{
    name: "negated dir-only rule: \"build\" (directory)",
    casefold: false,
    files: %{".gitignore" => "build/\n!build/\n"},
    path: "build",
    type: :directory,
    expected: false,
    rule: %{line: 2, pattern: "!build/", source: ".gitignore"}
  },
  %{
    name: "negated dir-only rule: \"build/x\" (file)",
    casefold: false,
    files: %{".gitignore" => "build/\n!build/\n"},
    path: "build/x",
    type: :file,
    expected: false,
    rule: nil
  },
  %{
    name: "star does not cross directories in path rules: \"foo/x/bar\" (directory)",
    casefold: false,
    files: %{".gitignore" => "foo/*/bar\n"},
    path: "foo/x/bar",
    type: :directory,
    expected: true,
    rule: %{line: 1, pattern: "foo/*/bar", source: ".gitignore"}
  },
  %{
    name: "star does not cross directories in path rules: \"foo/bar\" (file)",
    casefold: false,
    files: %{".gitignore" => "foo/*/bar\n"},
    path: "foo/bar",
    type: :file,
    expected: false,
    rule: nil
  },
  %{
    name: "star does not cross directories in path rules: \"foo/x/y/bar\" (file)",
    casefold: false,
    files: %{".gitignore" => "foo/*/bar\n"},
    path: "foo/x/y/bar",
    type: :file,
    expected: false,
    rule: nil
  },
  %{
    name: "nested gitignore negation: \"important.beam\" (file)",
    casefold: false,
    files: %{".gitignore" => "*.beam\n", "apps/web/.gitignore" => "!important.beam\n"},
    path: "important.beam",
    type: :file,
    expected: true,
    rule: %{line: 1, pattern: "*.beam", source: ".gitignore"}
  },
  %{
    name: "nested gitignore negation: \"apps/api/important.beam\" (file)",
    casefold: false,
    files: %{".gitignore" => "*.beam\n", "apps/web/.gitignore" => "!important.beam\n"},
    path: "apps/api/important.beam",
    type: :file,
    expected: true,
    rule: %{line: 1, pattern: "*.beam", source: ".gitignore"}
  },
  %{
    name: "nested gitignore negation: \"apps/web/important.beam\" (file)",
    casefold: false,
    files: %{".gitignore" => "*.beam\n", "apps/web/.gitignore" => "!important.beam\n"},
    path: "apps/web/important.beam",
    type: :file,
    expected: false,
    rule: %{line: 1, pattern: "!important.beam", source: "apps/web/.gitignore"}
  },
  %{
    name: "nested gitignore negation: \"apps/web/lib/important.beam\" (file)",
    casefold: false,
    files: %{".gitignore" => "*.beam\n", "apps/web/.gitignore" => "!important.beam\n"},
    path: "apps/web/lib/important.beam",
    type: :file,
    expected: false,
    rule: %{line: 1, pattern: "!important.beam", source: "apps/web/.gitignore"}
  },
  %{
    name: "nested gitignore anchoring: \"apps/web/tmp\" (directory)",
    casefold: false,
    files: %{"apps/web/.gitignore" => "/tmp\n"},
    path: "apps/web/tmp",
    type: :directory,
    expected: true,
    rule: %{line: 1, pattern: "/tmp", source: "apps/web/.gitignore"}
  },
  %{
    name: "nested gitignore anchoring: \"apps/web/lib/tmp\" (directory)",
    casefold: false,
    files: %{"apps/web/.gitignore" => "/tmp\n"},
    path: "apps/web/lib/tmp",
    type: :directory,
    expected: false,
    rule: nil
  },
  %{
    name: "nested gitignore anchoring: \"apps/tmp\" (directory)",
    casefold: false,
    files: %{"apps/web/.gitignore" => "/tmp\n"},
    path: "apps/tmp",
    type: :directory,
    expected: false,
    rule: nil
  },
  %{
    name: "deeper gitignore overrides shallower: \"debug.log\" (file)",
    casefold: false,
    files: %{".gitignore" => "*.log\n", "sub/.gitignore" => "!debug.log\n"},
    path: "debug.log",
    type: :file,
    expected: true,
    rule: %{line: 1, pattern: "*.log", source: ".gitignore"}
  },
  %{
    name: "deeper gitignore overrides shallower: \"sub/debug.log\" (file)",
    casefold: false,
    files: %{".gitignore" => "*.log\n", "sub/.gitignore" => "!debug.log\n"},
    path: "sub/debug.log",
    type: :file,
    expected: false,
    rule: %{line: 1, pattern: "!debug.log", source: "sub/.gitignore"}
  },
  %{
    name: "deeper gitignore overrides shallower: \"sub/other.log\" (file)",
    casefold: false,
    files: %{".gitignore" => "*.log\n", "sub/.gitignore" => "!debug.log\n"},
    path: "sub/other.log",
    type: :file,
    expected: true,
    rule: %{line: 1, pattern: "*.log", source: ".gitignore"}
  },
  %{
    name: "nested parent exclusion crosses gitignore layers: \"apps/web/build/keep.txt\" (file)",
    casefold: false,
    files: %{".gitignore" => "build/\n", "apps/web/.gitignore" => "!keep.txt\n"},
    path: "apps/web/build/keep.txt",
    type: :file,
    expected: true,
    rule: %{line: 1, pattern: "build/", source: ".gitignore"}
  },
  %{
    name: "nested parent exclusion crosses gitignore layers: \"apps/web/keep.txt\" (file)",
    casefold: false,
    files: %{".gitignore" => "build/\n", "apps/web/.gitignore" => "!keep.txt\n"},
    path: "apps/web/keep.txt",
    type: :file,
    expected: false,
    rule: %{line: 1, pattern: "!keep.txt", source: "apps/web/.gitignore"}
  },
  %{
    name: "casefold matching: \"readme.MD\" (file)",
    casefold: true,
    files: %{".gitignore" => "README.md\nBuild/\n*.Beam\n!Important.beam\n"},
    path: "readme.MD",
    type: :file,
    expected: true,
    rule: %{line: 1, pattern: "README.md", source: ".gitignore"}
  },
  %{
    name: "casefold matching: \"BUILD\" (directory)",
    casefold: true,
    files: %{".gitignore" => "README.md\nBuild/\n*.Beam\n!Important.beam\n"},
    path: "BUILD",
    type: :directory,
    expected: true,
    rule: %{line: 2, pattern: "Build/", source: ".gitignore"}
  },
  %{
    name: "casefold matching: \"foo.beam\" (file)",
    casefold: true,
    files: %{".gitignore" => "README.md\nBuild/\n*.Beam\n!Important.beam\n"},
    path: "foo.beam",
    type: :file,
    expected: true,
    rule: %{line: 3, pattern: "*.Beam", source: ".gitignore"}
  },
  %{
    name: "casefold matching: \"important.BEAM\" (file)",
    casefold: true,
    files: %{".gitignore" => "README.md\nBuild/\n*.Beam\n!Important.beam\n"},
    path: "important.BEAM",
    type: :file,
    expected: false,
    rule: %{line: 4, pattern: "!Important.beam", source: ".gitignore"}
  }
]
